CREATE DATABASE AMAZON_SALES ;
USE AMAZON_SALES;
SELECT * FROM SALES;

# DATA CLEANING:
-- RENAME COLUMN 
ALTER TABLE SALES
RENAME COLUMN ï»¿OrderID TO ORDER_ID;
SELECT * FROM SALES;

ALTER TABLE SALES
RENAME COLUMN OrderDate TO ORDER_DATE;

ALTER TABLE SALES RENAME COLUMN SellerID TO SELLER_ID;

ALTER TABLE SALES RENAME COLUMN CustomerID TO CUSTOMER_ID;

ALTER TABLE SALES RENAME COLUMN CustomerName TO CUSTOMER_NAME;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN ProductID TO PRODUCT_ID;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN ProductName TO PRODUCT_NAME;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN UnitPrice TO UNIT_PRICE;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN ShippingCost TO SHIPPING_COST; 
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN TotalAmount TO TOTAL_AMOUNT;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN PaymentMethod TO PAYMENT_METHOD;
SELECT * FROM SALES;

ALTER TABLE SALES RENAME COLUMN OrderStatus TO ORDER_STATUS;
SELECT * FROM SALES;

# CHECK NULL VALUES:
SELECT ORDER_ID FROM SALES WHERE ORDER_ID IS NULL;
SELECT * FROM SALES;

SELECT ORDER_DATE FROM SALES WHERE ORDER_DATE IS NULL;
SELECT * FROM SALES;

SELECT SELLER_ID FROM SALES WHERE SELLER_ID IS NULL;
SELECT * FROM SALES;

SELECT CUSTOMER_ID FROM SALES WHERE CUSTOMER_ID IS NULL;
SELECT * FROM SALES;

SELECT CUSTOMER_NAME FROM SALES WHERE CUSTOMER_NAME IS NULL;
SELECT * FROM SALES;

SELECT PRODUCT_ID FROM SALES WHERE PRODUCT_ID IS NULL;
SELECT * FROM SALES;

SELECT PRODUCT_NAME FROM SALES WHERE PRODUCT_NAME IS NULL;
SELECT * FROM SALES;

SELECT * FROM SALES WHERE CATEGORY IS NULL
	OR BRAND IS NULL
    OR QUANTITY IS NULL
    OR UNIT_PRICE IS NULL
    OR DISCOUNT IS NULL
    OR TAX IS NULL
    OR SHIPPING_COST IS NULL
    OR TOTAL_AMOUNT IS NULL
    OR PAYMENT_METHOD IS NULL
    OR ORDER_STATUS IS NULL
    OR CITY IS NULL
    OR STATE IS NULL
    OR COUNTRY IS NULL
LIMIT 1;

SELECT * FROM SALES;
-- -----------------------------------------------------------------------------------------
-- 1) SELECT TABLE
SELECT * FROM SALES ;

-- 2) COUNT OF ALL ORDERS
SELECT COUNT(*) AS TOTAL_ORDERS FROM SALES;         -- 1 LAKH TOTAL ORDERS

-- 3) FIND UNIQUE CUSTOMERS
SELECT COUNT(DISTINCT CUSTOMER_ID) AS "UNIQUE_CUSTOMERS" FROM SALES;   -- ANS: 43233

-- 4) FIND DIFFERENT CATEGORIES
SELECT distinct CATEGORY FROM SALES;

-- 5) CALCULATE TOTAL REVENUE GENERATED
SELECT ROUND(SUM(TOTAL_AMOUNT),2) AS 'TOTAL_REVENUE' FROM SALES ;
SELECT * FROM SALES ;

-- 6) CALCULATE TOTAL REVENUE BY CATEGORY
SELECT CATEGORY, ROUND(SUM(TOTAL_AMOUNT),2) AS 'REVENUE'
FROM SALES
GROUP BY CATEGORY
ORDER BY REVENUE DESC;

SELECT * FROM SALES ;

-- 7) TOP 5 SELLING PRODUCT 
SELECT PRODUCT_NAME, SUM(QUANTITY) AS "TOTAL_SOLD"
FROM SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;
SELECT * FROM SALES ;

-- 8) CALCULATE REVENUE BY CITY
SELECT CITY, ROUND(SUM(TOTAL_AMOUNT),2) AS "REVENUE"
FROM SALES
GROUP BY CITY
ORDER BY REVENUE DESC ;
SELECT * FROM SALES ;

-- 9) CALCULATE AVERAGE ORDER VALUE (AOV)
SELECT ROUND(SUM(TOTAL_AMOUNT),2) AS 'AOV'
FROM SALES;
SELECT * FROM SALES ;

-- 10) CALCULATE MONTHLY SALES TREND
SELECT month, ROUND(SUM(total_amount),2) AS revenue
FROM (SELECT DATE_FORMAT(order_date, '%Y-%m') AS MONTH, TOTAL_AMOUNT FROM SALES) AS MST
GROUP BY 1
ORDER BY 1;
SELECT * FROM SALES ;

-- 11) TOP 3 CUSTOMERS BY SPENDING
SELECT CUSTOMER_ID, CUSTOMER_NAME, ROUND(SUM(TOTAL_AMOUNT),2) AS "TOTAL_SPENT"
FROM SALES
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 3;
SELECT * FROM SALES ;

-- 12) CALCULATE PROFIT ANALYSIS AFTER (DISCOUNT + TAX + SHIPPING) APPLIED 
SELECT 
	ROUND(SUM(UNIT_PRICE * QUANTITY),2) AS 'GROSS_SALES' ,
	ROUND(SUM(DISCOUNT),2) AS 'DISCOUNT',
	ROUND(SUM(TAX),3) AS "TAX",
	ROUND(SUM(SHIPPING_COST),2) AS "SHIPPING_CHARGES",
	ROUND(SUM(TOTAL_AMOUNT),2) AS "REVENUE"
FROM SALES ;
SELECT * FROM SALES ;

-- 13) MOST PREFERRED PAYMENT METHOD
SELECT COUNT(*) AS 'TOTAL_ORDERS', PAYMENT_METHOD
FROM SALES
GROUP BY PAYMENT_METHOD
ORDER BY 1 DESC;

-- 14) CALCULATE ORDER STATUS DISTRIBUTION
SELECT COUNT(*) AS "TOTAL_ORDERS", ORDER_STATUS
FROM SALES
GROUP BY 2;

-- 15) CALCULATE CUSTOMER LIFETIME VALUE
SELECT CUSTOMER_ID, CUSTOMER_NAME, ROUND(SUM(TOTAL_AMOUNT),2) AS "LIFETIME_VALUE"
FROM SALES
GROUP BY 1,2
ORDER BY 3 DESC;

-- 16) REPEAT vs NEW CUSTOMERS
SELECT CUSTOMER_ID, COUNT(ORDER_ID) AS "ORDER_COUNT",
	CASE
		WHEN COUNT(ORDER_ID) = 1 THEN "NEW"
		ELSE 'REPEAT'
	END AS 'CUSTOMER_TYPE'
FROM SALES
GROUP BY CUSTOMER_ID;

SELECT * FROM SALES ;

-- 17) BEST PERFORMING BRAND IN EACH CATEGORY
SELECT CATEGORY, BRAND, ROUND(SUM(TOTAL_AMOUNT),2) AS "TOTAL_SALES"
FROM SALES
GROUP BY 1,2
ORDER BY 1,3 DESC;

-- 18) HIGHEST REVENUE DAY
SELECT ORDER_DATE, ROUND(SUM(TOTAL_AMOUNT),2) AS 'TOTAL_SALES' 
FROM SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

-- 19) RUNNING TOTAL OF SALES (WINDOWS FUNCTION)
SELECT ORDER_DATE,
    SUM(total_amount) AS "DAILY_SALES",
    SUM(SUM(total_amount)) OVER (ORDER BY order_date) AS "TOTAL_RUNNING"
FROM SALES
GROUP BY 1;

-- 20) RANK CUSTOMER BASED ON SPENDING 
SELECT CUSTOMER_ID, CUSTOMER_NAME,
SUM(TOTAL_AMOUNT) AS "TOTAL_SPENT",
RANK() OVER (ORDER BY SUM(TOTAL_AMOUNT) DESC) AS "RANK_NO"
FROM SALES
GROUP BY 1,2 ;

-- 21) FIND HIGHEST ORDER PER CUSTOMER
SELECT * FROM 
	(SELECT *, RANK() OVER (PARTITION BY CUSTOMER_ID ORDER BY TOTAL_AMOUNT DESC) AS "RNK" FROM SALES ) AS HIGHEST_RANK
WHERE RNK = 1; 

-- 22) DETECT LOW PERFORMING PRODUCTS
SELECT PRODUCT_NAME, SUM(QUANTITY) AS "TOTAL_SOLD" 
FROM SALES
GROUP BY 1
ORDER BY 2 ASC
LIMIT 5;

SELECT * FROM SALES;

-- 23) FIND CATEGORIES WHERE TOTAL REVENUE IS GREATER THAN 50,000 
SELECT CATEGORY,
	ROUND(SUM(TOTAL_AMOUNT),2) AS "REVENUE"
FROM SALES
GROUP BY 1
HAVING SUM(total_amount) > 50000;

-- ----------------------------------------------------------------------------------------------------------------------